plugins:
  - rubocop-performance
  - rubocop-rails

Layout/LineLength:
  Max: 100
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
